---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:12.0.2
  amd64: ghcr.io/hassio-addons/base-python:12.0.2
  armhf: ghcr.io/hassio-addons/base-python:12.0.2
  armv7: ghcr.io/hassio-addons/base-python:12.0.2
codenotary:
  signer: h.bougattaya1212@gmail.com
